# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff9f6d70a013373f6b12f700d760272bda21962204927edb814dbd78f7493ff2e67625648b18c3be14fcb81eedb4cc7e54f2d3b4f635a71a821149b06d8dfd33

test:
  secret_key_base: 1e568ec5728fae08b56519ac7fa6db26740db96139ecdfc76ebebc51501c2b4eb583ee678d2379f30e2bd7dcc6c2d6464f130e2d6539177f37b081923bf992d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
