# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c20f5907c213353ddddf887fbdfca515e91e7ff46c9058186f46c740b9c2fb8093c74ff0ba122cd394275cf8b5e165e327bf2b6e896cd2cef755e87c1b35a9a7

test:
  secret_key_base: da14ef238ff09cc67a589f30112dd4cc1694d6eb5ecb7b86c235a83d6e982f65072db92b8f6f679898d191424b475df401f704170c123a0c9da9d5c4fada96aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
