# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d804b59c00fff0cbbc093650a34f7e3eb3b2ae041e3116c865db7535b1f23098f312e7297e6898620c03243ddb393eaa04cee87f6cb94df3cb793e92b5c77e1

test:
  secret_key_base: 1ebb22b78f710ccad40a3aa24cc2e95f74732c99adce47073c669823d02284b7a6d4734016a5cc98d37771deedba2b6a31aae494979d4edf6c5fc0843a76499d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
